spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    database: oracle
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: chat
    password: 1234
    sql:
      init:
        encoding: UTF-8

# Server
server:
  port: 8080
  servlet:
    session:
      timeout: 120m